# Generated by Django 3.1.5 on 2021-03-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-SAW_score', 'title']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='summary',
        ),
        migrations.AddField(
            model_name='room',
            name='SAW_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='charge_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='distance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='room.region'),
        ),
    ]
