# Generated by Django 3.1.5 on 2021-03-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210301_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
