# Generated by Django 3.1.5 on 2021-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210301_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기도'), ('강원', '강원도'), ('충남', '충청남도'), ('충북', '충청북도'), ('전남', '전라남도'), ('전북', '전라북도'), ('제주', '제주도')], max_length=2, null=True),
        ),
    ]
