# Generated by Django 3.1.5 on 2021-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('facility', models.IntegerField()),
                ('usability', models.IntegerField()),
            ],
        ),
    ]
